### ISSUE TITLE
Energy sufficient but can't queue building

### ISSUE THREAD

**Issue by sunstello** [dark-galaxy/dark-galaxy#29]
Energy production is +20, and one building consuming -10 is allowed but not an additional -10.
![Screenshot 2022-12-28 at 10-00-25 Dark Galaxy - The ultimate Turn Based Strategy](https://user-images.githubusercontent.com/40995629/209831863-08e23413-17af-43e6-8f0b-ef6b98e4560d.png)

**Comment by Muffinman** [comment]
I just had another report of this. It stems from the fact that the pre-queue calculator does not know anything about the new energy research.

Those icons are being applied because the raw output (without research) is < +10.

**Comment by sunstello** [comment]
Thanks M. It was over a minute before turn change, and I just wanted to queue a mineral extractor before the new generator, but the queue "+" wouldn't let me. Glad you know how to fix it.

**Comment by Lord-Zeb** [comment]
No, there is definitely something wrong with the energy calculation formula.

I have on several occasions had a queue stop, because the energy reqirement have not been met - which it didn't early in the game, or other rounds, so this may be something with the new buildings, as well as other factors. And I have not researched any of the Energy tech levels either.

Also, I have been denied queueing things because the "new" energy counting algorithm doesn't seem to calculate freeing up Energy while demolishing buildings, which didn't happen earlier either.

**Comment by Muffinman** [comment]
Hi Zeb,

Sounds like yours might be a separate issue. Feel free to open a new issue with a screenshot of the planet details etc. so I can take a look.

**Comment by Muffinman** [comment]
Energy changes from this round have been reverted, so this should not be an issue going forward.
